### PR TITLE
Clean xsd template

### PR DESCRIPTION
**Pull request by iurisilvio**
I'm trying to simplify this XSD generation.

During this extraction, I found lots of code duplication (2d4380c).

I know it is a risk change, but it will be easier to future development.

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
I'll give the patch a spin but I agree - cleaning up the jinja template is sorrowly needed. Should I wait until #55  is merged?

**Comment by iurisilvio** [comment]
I prefer you wait for #55.

**Comment by FelixSchwarz** [comment]
@pope1ni retired soapbox today so a soapfish release would be nice (#74). As you mentioned the XSD refactoring is pretty invasive. Do you think I should merge your PR now or after the release? Due to time constraints a release is likely within the next two weeks or so.

**Comment by iurisilvio** [comment]
Do a good release now, after that we merge this PR. It is just lots of refactoring.

**Comment by pope1ni** [comment]
I'm currently working on a number of fixes that need to be in before the release and I'm happy to check this over before then.

**Comment by iurisilvio** [comment]
:+1: 

I think this pull request will help most of code generation changes in the future.

**Comment by FelixSchwarz** [comment]
@pope1ni @iurisilvio What's your feeling about merging this now? I think we can deal with any fallout as follow-up patches.

**Comment by iurisilvio** [comment]
This code is good. I'm using it in some cases. I don't know if @pope1ni validated it.

:+1: for merge

**Comment by FelixSchwarz** [comment]
merged, thank you very much @iurisilvio

**Pull request merged**
