### PR TITLE
Flask dispatcher

### PR DESCRIPTION
**Pull request by iurisilvio**
I'm already using soapfish with Flask in production, with this code.

It is at least one example about how to integrate it with Flask.

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
Hey, thank you very much for the great addition. Is it possible to add a trivial flask demo project which we could exercise in automated tests and/or some very simple documentation? Otherwise I fear that the code might be bitrotting soon enough.
(Don't worry about the failed tests - looks like Django doesn't support Python 2.6 anymore.)

**Comment by iurisilvio** [comment]
Sure! I'll add a small project example and some tests soon.

**Comment by iurisilvio** [comment]
I added some tests and an example. I moved the generated code to use in both Flask and Django apps.

**Comment by FelixSchwarz** [comment]
Thank you very much, looks nice now :-) I'll review the code later, might split up the big XML move into separate commits but otherwise I think you did a good job.

**Comment by iurisilvio** [comment]
I moved the generated code extraction to a separated commit.

**Pull request merged**
