### PR TITLE
Parse xsd:include and serve xsd files

### PR DESCRIPTION
**Pull request by iurisilvio**
I implemented the parser to xsd:include tags and the server response to XSD requests (`?xsd=myfile.xsd`)

It is a long diff because I had to rewrite some code to use locations instead of namespaces to identify `Schema_XXX` and to avoid duplicated schema processing.

I still want to write some tests here and reorganize my commits, but I need someone to check if my changes make sense.

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
I think the commits are fine but I have really little free time right now so please bear with me if this is a stupid question: Why are you using the location to identify a schema (in commit "Generate python code to included schemas.")? I assumed that a namespace should be better suited for that.

**Comment by FelixSchwarz** [comment]
Is this because of #49 ?

**Comment by iurisilvio** [comment]
Thanks for your feedback.

Yes, it is related with #49. I'll try to extract this change to a separated commit.

For includes, it is critical. The `xsd:include` means exactly it: include this schema in the same namespace.

http://www.w3schools.com/xml/el_include.asp

I identified `Schema_*` classes and file duplication based on filename instead of namespace. I used the `targetNamespace` as a fallback to the root schema (`location=None`).

**Comment by FelixSchwarz** [comment]
Yes for includes it makes sense. I'll run your changes with my own soapfish projects to see if these changes cause any regression for me.

**Comment by FelixSchwarz** [comment]
I cherry-picked 9e9cb6b in #63 which works fine for me. Should I try to merge this code here as-is or do you want to rework it?

**Comment by iurisilvio** [comment]
You can merge this one. I just rebased with your current master to fix merge conflicts.

**Comment by FelixSchwarz** [comment]
Just fyi: I'm seeing some errors when running the test suite for one of our products with the changes from this pull request.

      File ".../soapfish/py2xsd.py", line 246, in schema_validator
        resolver = SchemaResolver(schema)
      File ".../soapfish/py2xsd.py", line 230, in __init__
        self._map(schema)
      File ".../soapfish/py2xsd.py", line 233, in _map
        for item in (schema.imports + schema.includes):
    TypeError: can only concatenate list (not "tuple") to list

I'd like to check if this is a problem in my code or in soapfish.

**Comment by iurisilvio** [comment]
It is in soapfish. Both `imports` and `includes` defaults to empty tuples, but xsd2py generate these values as lists.

I fixed it converting both attributes to lists, but I still don't have a test for this use case.

Can you try again? I'll write a test for it.

**Comment by iurisilvio** [comment]
I changed `imports` and `includes` to always be lists. I fixed one test, it defined `imports` as tuple. So, it is already a test to this problem.

**Comment by iurisilvio** [comment]
I added another parameter to xsd2py generation. I need the `base_path` to normalize paths relative to it.

I avoid absolute paths to not leak your computer path structure, leading to a security issue.

**Comment by FelixSchwarz** [comment]
Thank you very much for updating your pull request. I'm sorry it too me so long before I could follow up here - and doubly sorry as I have some more questions.

The current code seems to assume that imports and includes are always lists. However a user (like me ;-) might have existing code which uses tuples. I think we should work with any iterable and convert the items on the fly if necessary.

Also using `[]` as a default value in a function definition always scares me - mutable default values caused a bug which took me about a week to track down and caused **a lot of** problems until I found it. Not sure how much hair I lost during while debugging it. We should not do that. Please.

**Comment by iurisilvio** [comment]
I agree with you. Default empty lists are dangerous! I did it because my `list + tuple` failed, but the right way to do it is with `itertools.chain`. I updated some code to use the `chain`.

**Comment by iurisilvio** [comment]
Also, I rebased with current master to fix some conflicts.

**Pull request merged**
