### PR TITLE
Update tests to Django>=1.9. Fix #65

### LINKED ISSUE #65: Django tests are broken
Django 1.9 released today and soapfish tests against the last version.

### PR DESCRIPTION
**Pull request by iurisilvio**

### CODE REVIEW

**Comment by iurisilvio** [comment]
I have a branch with all my pull requests merged (with some conflict resolution).

https://github.com/iurisilvio/soapfish/commits/dev

**Comment by FelixSchwarz** [comment]
Thank you very much for all your work, really appreciated. Also the updated branch is nice. I only did not use it as-is because I somehow dislike merge commits. I mean merges are of course fine but I try to avoid them for single commits. I encourage you to rebase so we get a linear history. As a rule of thumb I start using merge commits for complicated features (e.g. 3+ commits). Feel free to disagree and let me know if this cherry-picking is inconvenient to you - I can adapt :-)

**Comment by iurisilvio** [comment]
No problem at all. I did that branch only to continue working while you
didn't merged them.

**Comment by FelixSchwarz** [comment]
oh btw: I'd like to encourage you to add yourself to AUTHORS.txt (along with some modest commercial advertising if you like) and describe your changes in CHANGES.txt

**Pull request merged**
