### PR TITLE
Evaluate service location URL. %(scheme)s://%(host)s/ws

### LINKED ISSUE #57: Evaluate generated location
The generated file has some template URLs:

```python
location='%(scheme)s://%(host)s/myservice',
```

The SOAP dispatcher must render this location.

### PR DESCRIPTION
**Pull request by iurisilvio**
Fix #57

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
The code seems sensible but it triggers a build failure. Would you mind looking into that?
(btw: Thank you very much for all the tests you write)

**Comment by iurisilvio** [comment]
Travis is broken, because of this issue. http://bugs.python.org/issue7853

In some cases, Python send a string instead of an Exception to context manager `__exit__`.

**Comment by iurisilvio** [comment]
Just to be clear, I fixed the bugs travis triggered before.

Current bugs are not caused by my implementation. I think you should handle them in `pythonic_testcase`, but it is a workaround to a Python bug.

I tried to put a breakpoint code to understand the bug, but it works fine when I add the breakpoint. :)

**Comment by iurisilvio** [comment]
Related to this python bug: http://stackoverflow.com/questions/30012062/exc-value-parameter-from-exit-context-manager-is-string-instead-of-excep

**Comment by FelixSchwarz** [comment]
fixed with cherry-picking (0e4e2f36d94a213f914c74c1b49f6272d2fa031f)

**Pull request closed without merging**
